services:
  mysql:
    image: mysql:8.0.33
    container_name: order-service-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
