services:
  mysql:
    image: mysql:8.0.33
    container_name: inventory-service-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

